# override values
[forward]
# key = []
# mouse = []
# gamepad = []

[back]

[left]

[right]


[default]
[default.forward]
key = []
mouse = []
gamepad = []

[default.back]
key = []
mouse = []
gamepad = []

[default.left]
key = []
mouse = []
gamepad = []

[default.right]
key = []
mouse = []
gamepad = []
