name: TestVersionCache

on:
  workflow_dispatch:

jobs:
  # Build for wasm
  test_cache:
    runs-on: ubuntu-latest
    outputs:
      should-upload: ${{ steps.ensure-version.outputs.game-version }}

    steps:
      - uses: actions/checkout@v4
      - uses: olegtarasov/get-tag@v2.1.2
        id: get_version
      - name: ensure-version
        run: |
            if [[ -z ${{ steps.get_version.outputs.tag }} ]]; then
              echo "game-version=$GITHUB_SHA" >> $GITHUB_OUTPUT
            else
              echo "game-version=${{ steps.get_version.outputs.tag }}" >> $GITHUB_OUTPUT
            fi
  push_cached:
    runs-on: ubuntu-latest
    needs:
      - test_cache
    steps:
      - name: cache version
        run: |
            echo 'pub const GAME_VERSION: &str = "${{ needs.test_cache.outputs.should-upload }}";' > src/gen/mod.rs
            cat src/gen/mod.rs
